### PR TITLE
Relation fix

### LINKED ISSUE #60: Incorrect Apply operation
In the demo, if you write 7=7=7 you get an eq apply with the three sevens, but if you make it 7=7>=7 you still get an eq apply with the three sevens. This seems to be caused by the code on line 195 in parse.js:
```
if (relations.length > 1) {
      return {
            type: 'Apply',
            op: relations[0].op,
            args: args
     }
}
```
It's making the op equal to only what the op is for the first relation. This should only happen if all of the op's in relations are the same.

### PR DESCRIPTION
**Pull request by ericluap**
Allows for multiple relations that are different ('a=b>=c'). It starts with the last relation and adds the RHS of it to the apply node. Once a different relation is reached, a new apply node is made with the old one as the child. Finally, the LHS of the very first relation is added. Resolves #60

### CODE REVIEW

**Comment by k4b7** [comment]
I realize that there is something wrong with the current output, but suggested solution also feels wrong.  Given `a < b <= c`, the suggested AST (as an s-expr) is:
```
(< a (<= b c)
```
The problem with this is that each inequality takes two numeric values and returns a boolean value.  If we gave `a`, `b`, and `c` numeric values and evaluated we'd run into a problem when evaluating the `<`.

Current the parser does the "right" thing for `a < b < c` and produces:
```
(< a b c)
```
which should be interpreted as:
```
(a < b) && (b < c)
```
Following this pattern, the meaning of `a < b <= c` should be `(a < b) && (b <= c)`.  Arguable, the output for `a < b < c` should also be `(a < b) && (b < c)`.  When there are more inequality operators this should still produce a reasonable parse tree, e.g. `a < b <= c => d > e` should produce the following AST:
```
('and' (< a b) (<= b c) (>= c d) (d > e))
```
The unfortunate thing which requires more thought is how to avoid repeating symbols more than once in the output.  This is what MathML content markup does.  I can't think of an obviously better way to do this at the moment though.

**Comment by ericluap** [comment]
It definitely felt wrong when I had finished. Do we have a node with the 'and' operation?

**Comment by k4b7** [comment]
> Do we have a node with the 'and' operation?

There isn't a way to parse logical operators, yet, but the plan was to support `and`, `or`, `not`, etc. eventually.  Calling `build.applyNode('and', [leftOperand, rightOperand])` should do the trick.

**Comment by ericluap** [comment]
I've been a bit busy but I should be able to start working on this again soon.

**Comment by ericluap** [comment]
Should be all fixed now

**Comment by k4b7** [comment]
@SirFurness I'll review this this evening.  Sorry for the delay.

**Review by k4b7 — APPROVED** [review]
This seems to work, but it feels a little convoluted to reverse and unshift things. I'm going to accept this as is and if I have time I'll so what a straight ahead version might look like.

**Comment by ericluap** [comment]
@kevinbarabash You're definitely right. I was originally reversing and unshifting due to a different method I had thought of using. With this method, it really does not need to be reversed and can then just use push instead of unshift (other minor changes needed).

**Pull request merged**
