### PR TITLE
Subscript fix

### LINKED ISSUE #59: Incorrect subscript type
In the demo, when you type a1 it has the type of Identifier, but when you subscript something by a1 it now says that it is a number. This happens for any identifier that has a number in it.

### PR DESCRIPTION
**Pull request by ericluap**
Makes sure that subscripts are identified correctly as numbers or identifiers. Before isIdentifierToken and isNumberToken were just checking if they were contained anywhere in the string, but now they make sure they match with the whole string. This stops isNumberToken from classifying something as a number just because it contains a number. Resolves #59.

### CODE REVIEW

**Comment by k4b7** [comment]
@SirFurness could you add a test that fails without this change?

**Comment by ericluap** [comment]
Should be good now. I had a question about 'npm run build'. Whenever I run it, it says 'missing script: build'. Also, when I run 'node demo.js' it says 'Cannot find module'.

**Comment by k4b7** [comment]
> I had a question about 'npm run build'. Whenever I run it, it says 'missing script: build'. Also, when I run 'node demo.js' it says 'Cannot find module'.

The README is stale.  I'll fix that tonight.

**Comment by k4b7** [comment]
Thanks for adding a test.

**Pull request merged**
